agent: "Q-learning"
maze_file: "mazes/10x10.txt"

reward:
  mode: "manhattan"
  goal_reward: 1.0
  eta: 0.01
  beta: 0.1

hyperparameters:
  learning_rate: 0.2
  discount_rate: 0.999
  q_init_strategy: "random_negative"
  q_init_random_low: -0.5
  q_init_random_high: 0.0
  epsilon_policy: "performance_based"
  epsilon: 1.0
  epsilon_min: 0.05
  epsilon_decay: 0.99

training:
  episodes: 800
  max_steps: 200
  render: False
  render_heatmap: False

evaluation:
  enabled: True
  num_videos: 5
  episodes: 1
  max_steps: 50
  save_video: True
  video_heatmap: True
  display: False
  fps: 8

viz:
  num_plots: 4
  window_size: null
